<?php
/**
 * SUMOHeavy_BingTracking
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to support@sumoheavy.com so we can send you a copy immediately.
 *
 * @category   SUMOHeavy
 * @package    SUMOHeavy_BingTracking
 * @copyright  Copyright 2013 SUMO Heavy Industries, LLC
 * @license    http://opensource.org/licenses/osl-3.0.php
 * @author     Sean Kennedy <support@sumoheavy.com>
 */
$baseUrl    = str_replace('shop/', '', Mage::getBaseUrl());
$currentUrl = Mage::helper('core/url')->getCurrentUrl();

/**
 * Homepage (WordPress)
 */
if($baseUrl == $currentUrl):
    $domainId = Mage::getStoreConfig(
        'sumoheavy_bingtracking/settings/domain_id'
    );
    $adsGuid = Mage::getStoreConfig(
        'sumoheavy_bingtracking/settings/ads_guid'
    );
    $actionId = Mage::getStoreConfig(
        'sumoheavy_bingtracking/homepage/action_id'
    );
    if(Mage::getStoreConfig('sumoheavy_bingtracking/homepage/enabled')
    && $domainId
    && $adsGuid
    && $actionId):
        ?>
        <script type="text/javascript">if (!window.mstag) mstag = {loadTag : function(){},time : (new Date()).getTime()};</script>
        <script id="mstag_tops" type="text/javascript" src="//flex.atdmt.com/mstag/site/<?php echo $adsGuid; ?>/mstag.js"></script>
        <script type="text/javascript">
            mstag.loadTag(
                "analytics",
                {
                    dedup: "1",
                    domainId: "<?php echo $domainId; ?>",
                    type: "1",
                    taxcost: "",
                    shippingcost: "",
                    actionid: "<?php echo $actionId; ?>"
                }
            )
        </script>
        <noscript><iframe src="//flex.atdmt.com/mstag/tag/<?php echo $adsGuid; ?>/analytics.html?dedup=1&domainId=<?php echo $domainId; ?>&type=1&taxcost=&shippingcost=&actionid=<?php echo $actionId; ?>" frameborder="0" scrolling="no" width="1" height="1" style="visibility:hidden;display:none"></iframe></noscript>
        <?php
    endif;
endif;
?>
